REGISTERCREW_MAPPING = {
    'Id': 'Id',
    'NIP': 'EmployeeIdNumber',
    'FirstName': 'FullName',
    'NickName': None,
    'Email': 'RegEmail',
    'Password': 'TemporaryPassword',
    'PositionId': 'RegDivisionId',
    'StatusRegister': 'CurrentStatusId',
    'Address': 'RegAddress',
    'BirthLoc': 'RegPlaceOfBirth',
    'BirthDate': 'RegDateOfBirth',
    'BirthPlaceId': None,
    'CellPhone': 'RegPhoneNo',
    'Gender': 'RegGender',
    'HomePhone': None,
    'IdentityCardNo': 'RegIdCardNo',
    'ReligionId': 'RegReligionId',
    'AddressKtp': 'RegAddress',
    'NPWP': 'RegNPWP',
    'KKNumber': 'RegFamilyCardNo',
    'BPJSKetNumber': 'RegBPJSTKNo',
    'BPJSKesNumber': 'RegBPJSKesNo',
    'BankId': 'RegBankId1',
    'BankAccountNo': 'RegBankAccount1',
    'BankAccountName': 'RegBankAccountName1',
    'BankId2': 'RegBankId2',
    'BankAccountNo2': 'RegBankAccount2',
    'BankAccountName2': 'RegBankAccountName2',
    'Foto': 'RegPhotoId',
    'MaritalStatusId': 'RegMaritalStatusId',
    'ShipId': None,
    'OnBoard': 'AvailableForm',
    'OffBoard': 'AvailableUntil',
    'ShipRejection': None,
    'SeaManBook': 'RegSeamanBookNo',
    'PasporBook': 'RegIdPassport',
    'McuIssued': None,
    'RegShipStatusId': None,
    'CompanyId': None,
    'CreatedAt': 'Created',
    'UpdatedAt': 'Modified',
    'IsDeleted': 'IsDeleted'
}

REGISTERCREW_ADDITIONAL = {
    'Kolom baru': 'nilai'
}
